### ISSUE TITLE
0.7.3 brakes compilation process 

### ISSUE THREAD

**Issue by kurotych** [helium/helium-crypto-rs#63]
Hi guys.
 After updating to 0.7.3 version compilation is broken. 
 It looks like `0.4.0` version rsa is conflicting with another `0.6.1` version which is used by another dependecy in our project. 
 
Currently, we have rolled back to 0.7.2.
 
 ### STR
 Try to compile project with next dependencies:
 ```
 [dependencies]
helium-crypto = "=0.7.3"
google-cloud-default = { version = "=0.1.1", features = ["storage"] }
```
 
 **Log**
 
  ```
      Compiling rsa v0.4.0
error[E0432]: unresolved imports `self::encode::PrivateKeyPemEncoding`, `self::encode::PublicKeyPemEncoding`
   --> /home/kurotych/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsa-0.4.0/src/lib.rs:120:25
    |
120 |     PrivateKeyEncoding, PrivateKeyPemEncoding, PublicKeyEncoding, PublicKeyPemEncoding,
    |                         ^^^^^^^^^^^^^^^^^^^^^                     ^^^^^^^^^^^^^^^^^^^^ no `PublicKeyPemEncoding` in `encode`
    |                         |
    |                         no `PrivateKeyPemEncoding` in `encode`
    |
help: a similar name exists in the module
    |
120 |     PrivateKeyEncoding, PrivateKeyEncoding, PublicKeyEncoding, PublicKeyPemEncoding,
    |                         ~~~~~~~~~~~~~~~~~~
help: a similar name exists in the module
    |
120 |     PrivateKeyEncoding, PrivateKeyPemEncoding, PublicKeyEncoding, PublicKeyEncoding,
    |                                                                   ~~~~~~~~~~~~~~~~~

error[E0432]: unresolved import `pem`
 --> /home/kurotych/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsa-0.4.0/src/encode.rs:9:5
  |
9 | use pem::{EncodeConfig, LineEnding};
  |     ^^^ use of undeclared crate or module `pem`

error[E0405]: cannot find trait `PublicKeyPemEncoding` in this scope
   --> /home/kurotych/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsa-0.4.0/src/encode.rs:219:6
    |
219 | impl PublicKeyPemEncoding for RSAPublicKey {
    |      ^^^^^^^^^^^^^^^^^^^^ help: a trait with a similar name exists: `PublicKeyEncoding`
...
308 | pub trait PublicKeyEncoding: PublicKey {
    | -------------------------------------- similarly named trait `PublicKeyEncoding` defined here

Some errors have detailed explanations: E0405, E0432.
For more information about an error, try `rustc --explain E0405`.
error: could not compile `rsa` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...

    ```

**Comment by madninja** [comment]
If I need this right, you will need to adapt to the RSA 0.4 api vs using the 0.9 version like we were too.. RSA 0.4 is required to be able to support both our and Solana applications. 

Equivalent working structs and traits are defined in RSA 0.4 for the errors you mentioned

**Comment by kurotych** [comment]
> you will need to adapt to the RSA 0.4 api vs using the 0.9 version like we were too

I have no code that uses the directly RSA library in my project.
I've just tried to compile an empty project with these two dependencies  and it fails

```
[dependencies]
helium-crypto = "=0.7.3"
google-cloud-default = { version = "=0.1.1", features = ["storage"] }
```

**Comment by madninja** [comment]
hmm odd.. does your project need RSA helium keypair support at all?

**Comment by kurotych** [comment]
> does your project need RSA helium keypair support at all?

No, it doesn't. RSA feature was enabled by default. (https://github.com/helium/helium-crypto-rs/blob/main/Cargo.toml#L36) 

`helium-crypto = { version = "0.7.3", default-features = false }` helped to resolve issue. 

Thank you!

**Comment by madninja** [comment]
Glad that resolved it!
